server:
  port: 9011
  servlet:
    context-path: /boot-lanuch

spring:
  jackson:
    # 全局配置 json 时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.17.131:3306/launch?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin
# http://localhost:9012/management/actuator/mappings
# http://localhost:9012/management/actuator/beans
management:
  server:
    port: 9012
    servlet:
      context-path: /management
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleteFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.mingyang.bootlaunch: INFO # 日志级别
  config: classpath:logback-spring.xml